name: Go

on:
  push:
    tags:
      - v*

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux AMD64
      run: make compile os=linux arch=amd64
