name: Go

on:
  push:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux AMD64
      run: make compile os=linux arch=amd64 version=${{ github.ref }}

    - name: Build Windows AMD64
      run: make compile os=windows arch=amd64 version=${{ github.ref }}

    - name: Build Mac AMD64
      run: make compile os=darwin arch=amd64 version=${{ github.ref }}

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
